
#
# This LookML file was generated by AtScale on 2022-02-23T19:12:57.675679Z
#
# AtScale engine version: 2021.4.0.11186
# AtScale DesignCenter version: 2021.4.0.18787
# AtScale version: 2021.4.0.4227
# Organization: default
# Project: RS Model for Demo

connection: "atscale_server_kaleb"
label: "RS Model for Demo"


include: "/views/RS_Model_for_Demo/KLN_Demo_Cube.view.lkml"


explore: KLN_Demo_Cube {
  label: "KLN Demo Cube"
}

