
#
# This LookML file was generated by AtScale on 2022-02-23T14:41:40.656383Z
#
# AtScale engine version: 2021.4.0.11186
# AtScale DesignCenter version: 2021.4.0.18787
# AtScale version: 2021.4.0.4227
# Organization: default
# Project: Workshop_KLN

connection: "atscale_server_kaleb"
label: "Workshop_KLN"


include: "/views/Workshop__KLN/Workshop__KLN.view.lkml"


explore: Workshop_KLN {
  label: "Workshop_KLN"
}

